version: '3.8'
services:
  notification-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=mdpatil2004@gmail.com
      - SMTP_PASSWORD=hfml pxnr ppjo qeva
      - SENDER_EMAIL=mdpatil2004@gmail.com